[package]
name = "shoshin_cairo_1"
version = "0.1.0"
description = "A Cairo 1.0 port of Shoshin"

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test ."
# Add your own custom commands and run them with scarb run <command>

# Uncomment if you want to use dependencies
# Note: currently testing doesn't work with dependencies
# [dependencies]
# quaireaux = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }
